Repository Monday-Rocket/ac_project_app, pull requests merged in 2023-01, with the labels that each got.

#66 [fix/#62 fix/#65] 토스트 (스낵바) 팝업 위치 수정 및 저장시 토스트 뜨도록 수정
  lib/const/consts.dart
  lib/ui/page/home/home_page.dart
  lib/ui/page/my_folder/my_folder_page.dart
  lib/ui/page/my_page/my_page.dart
  lib/ui/view/email_login_view.dart
  lib/ui/view/email_sign_up_view.dart
  lib/ui/view/home_view.dart
  lib/ui/view/login_view.dart
  lib/ui/view/report_view.dart
  lib/ui/view/upload_view.dart
  lib/ui/widget/bottom_dialog.dart
  lib/ui/widget/bottom_toast.dart
Labels: fix

#73 [fix/#72] 잔여 이슈 해결
  .github/workflows/ci.yml
  android/app/build.gradle
  ios/Runner.xcodeproj/project.pbxproj
  lib/cubits/links/upload_link_cubit.dart
  lib/provider/share_data_provider.dart
  lib/ui/view/link_detail_view.dart
  lib/util/string_utils.dart
Labels: fix

#74 1.0.19 배포
  .github/workflows/ci.yml
  android/app/build.gradle
  android/fastlane/Appfile
  android/fastlane/Fastfile
  ios/Runner.xcodeproj/project.pbxproj
  ios/fastlane/Fastfile
  lib/const/consts.dart
  lib/cubits/links/upload_link_cubit.dart
  lib/provider/share_data_provider.dart
  lib/ui/page/home/home_page.dart
  lib/ui/page/my_folder/my_folder_page.dart
  lib/ui/page/my_page/my_page.dart
  lib/ui/view/email_login_view.dart
  lib/ui/view/email_sign_up_view.dart
  lib/ui/view/home_view.dart
  lib/ui/view/link_detail_view.dart
  lib/ui/view/login_view.dart
  lib/ui/view/report_view.dart
  lib/ui/view/upload_view.dart
  lib/ui/widget/bottom_dialog.dart
  lib/ui/widget/bottom_toast.dart
  lib/util/string_utils.dart
  pubspec.yaml
Labels: version

#75 [fix/#72] 잔여 이슈 추가 해결
  android/app/src/main/kotlin/com/mr/ac_project_app/data/ShareDbHelper.kt
  android/app/src/main/kotlin/com/mr/ac_project_app/view/folder/NewFolderActivity.kt
  ios/Extension/Base.lproj/MainInterface.storyboard
  ios/Extension/Info.plist
  ios/Extension/ViewController/NewFolderViewController.swift
  ios/Runner.xcodeproj/project.pbxproj
  lib/provider/api/folders/link_api.dart
  lib/ui/page/my_folder/my_folder_page.dart
Labels: fix

#76 1.0.20 업데이트
  android/app/src/main/kotlin/com/mr/ac_project_app/data/ShareDbHelper.kt
  android/app/src/main/kotlin/com/mr/ac_project_app/view/folder/NewFolderActivity.kt
  ios/Extension/Base.lproj/MainInterface.storyboard
  ios/Extension/Info.plist
  ios/Extension/ViewController/NewFolderViewController.swift
  ios/Runner.xcodeproj/project.pbxproj
  lib/provider/api/folders/link_api.dart
  lib/ui/page/my_folder/my_folder_page.dart
  pubspec.yaml
Labels: version

#79 [fix/#72] 홈화면, 피드화면 스크롤 오류 수정
  ios/Extension/Info.plist
  ios/Runner.xcodeproj/project.pbxproj
  lib/cubits/feed/feed_view_cubit.dart
  lib/cubits/links/links_from_selected_job_group_cubit.dart
  lib/ui/page/home/home_page.dart
  lib/ui/view/user_feed_view.dart
Labels: fix

#80 1.0.21 업데이트
  ios/Extension/Info.plist
  ios/Runner.xcodeproj/project.pbxproj
  lib/cubits/feed/feed_view_cubit.dart
  lib/cubits/links/links_from_selected_job_group_cubit.dart
  lib/ui/page/home/home_page.dart
  lib/ui/view/user_feed_view.dart
  pubspec.yaml
Labels: version

#89 [fix/#88] 버튼 그림자 디자인 맞춰서 수정
  lib/ui/view/change_profile_view.dart
  lib/ui/view/upload_view.dart
  lib/ui/widget/add_folder/show_add_folder_dialog.dart
  lib/ui/widget/buttons/bottom_sheet_button.dart
  lib/ui/widget/dialog.dart
Labels: fix

#91 [fix/#86, fix/#90] 1.0.22 App Store 심사 대응
  android/app/src/main/kotlin/com/mr/ac_project_app/view/share/ShareActivity.kt
  android/app/src/main/res/drawable-hdpi/ic_notice.png
  android/app/src/main/res/drawable-hdpi/ic_save_success.png
  android/app/src/main/res/drawable-xhdpi/ic_notice.png
  android/app/src/main/res/drawable-xhdpi/ic_save_success.png
  android/app/src/main/res/drawable-xxhdpi/ic_notice.png
  android/app/src/main/res/drawable-xxhdpi/ic_save_success.png
  android/app/src/main/res/drawable-xxxhdpi/ic_notice.png
  android/app/src/main/res/drawable-xxxhdpi/ic_save_success.png
  android/app/src/main/res/drawable/ic_notice.png
  android/app/src/main/res/drawable/ic_save_success.png
  android/app/src/main/res/drawable/notice_text_back.xml
  android/app/src/main/res/layout/activity_share.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  ios/.gitattributes
  ios/Extension/Assets.xcassets/grey/grey50.colorset/Contents.json
  ios/Extension/Assets.xcassets/grey/grey600.colorset/Contents.json
  ios/Extension/Base.lproj/MainInterface.storyboard
  ios/Extension/Custom/StringExtension.swift
  ios/Extension/Custom/URLExtension.swift
  ios/Extension/Images.xcassets/ic_notice.imageset/Contents.json
  ios/Extension/Images.xcassets/ic_notice.imageset/ic_notice.svg
  ios/Extension/ViewController/ShareViewController.swift
  ios/Runner.xcodeproj/project.pbxproj
  lib/const/colors.dart
  lib/const/strings.dart
  lib/ui/view/change_profile_view.dart
  lib/ui/view/report_view.dart
  lib/ui/view/upload_view.dart
  lib/ui/widget/bottom_toast.dart
Labels: fix

#92 1.0.23 업데이트
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/mr/ac_project_app/MainActivity.kt
  android/app/src/main/kotlin/com/mr/ac_project_app/utils/Utils.kt
  android/app/src/main/kotlin/com/mr/ac_project_app/view/share/ShareActivity.kt
  android/app/src/main/kotlin/com/mr/ac_project_app/view/share/ShareViewModel.kt
  android/app/src/main/res/drawable-hdpi/ic_notice.png
  android/app/src/main/res/drawable-hdpi/ic_save_success.png
  android/app/src/main/res/drawable-xhdpi/ic_notice.png
  android/app/src/main/res/drawable-xhdpi/ic_save_success.png
  android/app/src/main/res/drawable-xxhdpi/ic_notice.png
  android/app/src/main/res/drawable-xxhdpi/ic_save_success.png
  android/app/src/main/res/drawable-xxxhdpi/ic_notice.png
  android/app/src/main/res/drawable-xxxhdpi/ic_save_success.png
  android/app/src/main/res/drawable/ic_notice.png
  android/app/src/main/res/drawable/ic_save_success.png
  android/app/src/main/res/drawable/notice_text_back.xml
  android/app/src/main/res/layout/activity_share.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  ios/.gitattributes
  ios/Extension/Assets.xcassets/grey/grey50.colorset/Contents.json
  ios/Extension/Assets.xcassets/grey/grey600.colorset/Contents.json
  ios/Extension/Base.lproj/MainInterface.storyboard
  ios/Extension/Custom/StringExtension.swift
  ios/Extension/Custom/URLExtension.swift
  ios/Extension/Images.xcassets/ic_notice.imageset/Contents.json
  ios/Extension/Images.xcassets/ic_notice.imageset/ic_notice.svg
  ios/Extension/Info.plist
  ios/Extension/ViewController/ShareViewController.swift
  ios/Runner.xcodeproj/project.pbxproj
  lib/const/colors.dart
  lib/const/strings.dart
  lib/cubits/links/upload_link_cubit.dart
  lib/cubits/url_data_cubit.dart
  lib/provider/login/email_login.dart
  lib/provider/share_data_provider.dart
  lib/ui/view/change_profile_view.dart
  lib/ui/view/report_view.dart
  lib/ui/view/upload_view.dart
  lib/ui/widget/add_folder/show_add_folder_dialog.dart
  lib/ui/widget/bottom_toast.dart
  lib/ui/widget/buttons/bottom_sheet_button.dart
  lib/ui/widget/dialog.dart
  lib/util/string_utils.dart
  pubspec.yaml
  test/provider/api/folder/folder_api.dart
Labels: version

#96 [fix/#93] PlayStore 앱 배포 시 경고 제거를 위한 작업
  .github/workflows/cicd.yml
  android/app/build.gradle
  android/fastlane/Fastfile
Labels: fix, refactor

#95 [fix/#94] playstore api key 파일명 변경
  .github/workflows/cicd.yml
  android/fastlane/Appfile
Labels: fix

#99 [fix/#98] 2차 QA 이슈 수정
  .env
  android/app/src/main/kotlin/com/mr/ac_project_app/dialog/MessageDialog.kt
  android/app/src/main/kotlin/com/mr/ac_project_app/view/comment/CommentActivity.kt
  ios/.gitattributes
  ios/Extension/Dialog/LinkSavedDialogViewController.swift
  ios/Runner.xcodeproj/project.pbxproj
  lib/ui/page/my_folder/my_folder_page.dart
  lib/ui/view/upload_view.dart
  lib/ui/widget/add_folder/folder_add_title.dart
  lib/ui/widget/add_folder/show_add_folder_dialog.dart
  lib/ui/widget/bottom_dialog.dart
  lib/util/list_utils.dart
Labels: fix

#103 [feat/#102] 튜토리얼 추가
  assets/tutorials/1.5x/tutorial1.png
  assets/tutorials/1.5x/tutorial2.png
  assets/tutorials/1.5x/tutorial3.png
  assets/tutorials/1.5x/tutorial4.png
  assets/tutorials/2.0x/tutorial1.png
  assets/tutorials/2.0x/tutorial2.png
  assets/tutorials/2.0x/tutorial3.png
  assets/tutorials/2.0x/tutorial4.png
  assets/tutorials/3.0x/tutorial1.png
  assets/tutorials/3.0x/tutorial2.png
  assets/tutorials/3.0x/tutorial3.png
  assets/tutorials/3.0x/tutorial4.png
  assets/tutorials/tutorial1.png
  assets/tutorials/tutorial2.png
  assets/tutorials/tutorial3.png
  assets/tutorials/tutorial4.png
  lib/const/colors.dart
  lib/const/strings.dart
  lib/initial_settings.dart
  lib/main.dart
  lib/models/tutorial/tutorial.dart
  lib/routes.dart
  lib/ui/view/links/home_view.dart
  lib/ui/view/links/link_detail_view.dart
  lib/ui/view/links/my_link_view.dart
  lib/ui/view/links/search_view.dart
  lib/ui/view/links/user_feed_view.dart
  lib/ui/view/splash_view.dart
  lib/ui/view/tutorial_view.dart
  lib/ui/view/user/change_profile_view.dart
  lib/ui/view/user/email_login_view.dart
  lib/ui/view/user/email_sign_up_view.dart
  lib/ui/view/user/login_view.dart
  lib/ui/view/user/sign_up_job_view.dart
  lib/ui/view/user/sign_up_nickname_view.dart
  lib/ui/widget/add_folder/horizontal_folder_list.dart
  lib/ui/widget/buttons/bottom_sheet_button.dart
  pubspec.yaml
Labels: feat, refactor

#104 1.0.25 업데이트
  .github/workflows/cicd.yml
  android/fastlane/Fastfile
  assets/tutorials/1.5x/tutorial1.png
  assets/tutorials/1.5x/tutorial2.png
  assets/tutorials/1.5x/tutorial3.png
  assets/tutorials/1.5x/tutorial4.png
  assets/tutorials/2.0x/tutorial1.png
  assets/tutorials/2.0x/tutorial2.png
  assets/tutorials/2.0x/tutorial3.png
  assets/tutorials/2.0x/tutorial4.png
  assets/tutorials/3.0x/tutorial1.png
  assets/tutorials/3.0x/tutorial2.png
  assets/tutorials/3.0x/tutorial3.png
  assets/tutorials/3.0x/tutorial4.png
  assets/tutorials/tutorial1.png
  assets/tutorials/tutorial2.png
  assets/tutorials/tutorial3.png
  assets/tutorials/tutorial4.png
  lib/const/colors.dart
  lib/const/strings.dart
  lib/initial_settings.dart
  lib/main.dart
  lib/models/tutorial/tutorial.dart
  lib/routes.dart
  lib/ui/view/links/home_view.dart
  lib/ui/view/links/link_detail_view.dart
  lib/ui/view/links/my_link_view.dart
  lib/ui/view/links/search_view.dart
  lib/ui/view/links/user_feed_view.dart
  lib/ui/view/splash_view.dart
  lib/ui/view/tutorial_view.dart
  lib/ui/view/user/change_profile_view.dart
  lib/ui/view/user/email_login_view.dart
  lib/ui/view/user/email_sign_up_view.dart
  lib/ui/view/user/login_view.dart
  lib/ui/view/user/sign_up_job_view.dart
  lib/ui/view/user/sign_up_nickname_view.dart
  lib/ui/widget/add_folder/horizontal_folder_list.dart
  lib/ui/widget/buttons/bottom_sheet_button.dart
  pubspec.yaml
Labels: version

#105 [hotfix] 튜토리얼 화면 잘림 수정
  lib/initial_settings.dart
  lib/ui/view/splash_view.dart
  lib/ui/view/tutorial_view.dart
  pubspec.yaml
Labels: bug, version

#106 1.0.26 업데이트
  lib/initial_settings.dart
  lib/ui/view/splash_view.dart
  lib/ui/view/tutorial_view.dart
  pubspec.yaml
Labels: version
