Repository Monday-Rocket/ac_project_app, pull requests merged in 2023-02, with the labels that each got.

#110 [refactor/#107] 홈화면 두번째 탭에 자신의 직업군이 나오도록 수정
  lib/cubits/home/get_job_list_cubit.dart
  lib/cubits/links/links_from_selected_job_group_cubit.dart
  lib/cubits/profile/profile_info_cubit.dart
  lib/models/profile/profile.dart
  lib/provider/api/folders/link_api.dart
  lib/ui/page/home/home_page.dart
  lib/ui/page/my_page/my_page.dart
  lib/ui/view/links/home_view.dart
  lib/util/list_utils.dart
Labels: feat, refactor

#114 Feat/#109 폴더 이름 수정
  lib/cubits/folders/get_my_folders_cubit.dart
  lib/provider/api/folders/folder_api.dart
  lib/provider/share_db.dart
  lib/ui/page/my_folder/my_folder_page.dart
  lib/ui/view/upload_view.dart
  lib/ui/widget/add_folder/folder_add_title.dart
  lib/ui/widget/add_folder/horizontal_folder_list.dart
  lib/ui/widget/bottom_toast.dart
  lib/ui/widget/rename_folder/show_rename_folder_dialog.dart
Labels: feat

#113 [refactor/#108] 2차 QA 개선 - 로딩 및 기타 UI/UX 개선
  assets/animations/loading.json
  ios/Runner.xcodeproj/project.pbxproj
  lib/animtaion_test.dart
  lib/cubits/home/search_links_cubit.dart
  lib/cubits/login/login_cubit.dart
  lib/provider/login/email_login.dart
  lib/ui/view/links/search_view.dart
  lib/ui/view/upload_view.dart
  lib/ui/view/user/login_view.dart
  lib/ui/view/user/sign_up_job_view.dart
  lib/util/url_valid.dart
  pubspec.yaml
Labels: fix, refactor

#118 [refactor/#112] 무한 스크롤 로딩 홈화면 반영, 업로드 화면 로딩
  lib/cubits/links/links_from_selected_job_group_cubit.dart
  lib/ui/page/home/home_page.dart
  lib/ui/view/upload_view.dart
  lib/ui/widget/loading.dart
  lib/util/url_valid.dart
Labels: refactor

#120 [refactor/#119] 추가된 secrets 파일 github Actions workflow 추가
  .github/workflows/cicd.yml
  android/app/build.gradle
Labels: refactor

#121 [feat/#117] my_link 화면에서 슬라이드하여 링크 삭제기능 추가
  lib/ui/view/links/my_link_view.dart
  lib/ui/widget/slidable/link_slidable_widget.dart
  pubspec.yaml
Labels: feat

#127 [refactor/#126] 1.0.28 업데이트
  ios/Runner.xcodeproj/project.pbxproj
  lib/const/strings.dart
  lib/cubits/links/upload_link_cubit.dart
  lib/models/link/link.dart
  lib/models/link/link.g.dart
  lib/models/link/upload_type.dart
  lib/models/result.freezed.dart
  lib/models/user/user.freezed.dart
  lib/provider/api/folders/link_api.dart
  lib/ui/view/upload_view.dart
  pubspec.yaml
Labels: refactor, version

#130 [fix/#129] 카카오, 네이버 로그아웃 시 동일 계정으로 자동 로그인 되지 않도록 로그아웃 로직 개선
  lib/provider/api/user/user_api.dart
  lib/provider/login/kakao_login.dart
  lib/provider/login/naver_login.dart
  lib/provider/logout.dart
  lib/ui/page/my_page/my_page.dart
  pubspec.yaml
Labels: fix

#133 [fix/#132] 1.0.30 업데이트
  assets/images/1.5x/apple_icon.png
  assets/images/2.0x/apple_icon.png
  assets/images/3.0x/apple_icon.png
  assets/images/apple_icon.png
  lib/gen/assets.gen.dart
  lib/gen/fonts.gen.dart
  lib/ui/view/user/login_view.dart
  lib/ui/widget/buttons/apple/apple_login_button.dart
  pubspec.yaml
Labels: fix, version

#136 [fix/#135] 업로드 화면에서 링크 업로드 시 현재 시간 24시간 기준으로 받아오기
  lib/util/string_utils.dart
  pubspec.yaml
Labels: fix

#139 [fix/#138] 1.0.32 업데이트
  lib/provider/api/user/profile_api.dart
  lib/ui/view/upload_view.dart
  lib/util/string_utils.dart
  pubspec.yaml
Labels: fix
