Repository Monday-Rocket/ac_project_app, pull requests merged in 2023-03, with the labels that each got.

#142 [fix/#141] 리팩토링 및 앱스토어에 노출되는 기본 언어 설정 변경
  .github/workflows/cicd.yml
  README.md
  cicd.png
  ios/Runner.xcodeproj/project.pbxproj
  lib/const/consts.dart
  lib/const/resource.dart
  lib/const/strings.dart
  lib/cubits/profile/profile_images_cubit.dart
  lib/provider/login/email_login.dart
  lib/ui/page/home/home_page.dart
  lib/ui/page/my_folder/my_folder_page.dart
  lib/ui/page/my_page/my_page.dart
  lib/ui/view/links/home_view.dart
  lib/ui/view/links/link_detail_view.dart
  lib/ui/view/links/my_link_view.dart
  lib/ui/view/links/search_view.dart
  lib/ui/view/links/user_feed_view.dart
  lib/ui/view/report_view.dart
  lib/ui/view/splash_view.dart
  lib/ui/view/upload_view.dart
  lib/ui/view/user/change_profile_view.dart
  lib/ui/view/user/email_login_view.dart
  lib/ui/view/user/login_view.dart
  lib/ui/view/user/sign_up_job_view.dart
  lib/ui/widget/add_folder/folder_add_title.dart
  lib/ui/widget/add_folder/horizontal_folder_list.dart
  lib/ui/widget/add_folder/show_add_folder_dialog.dart
  lib/ui/widget/bottom_dialog.dart
  lib/ui/widget/custom_reorderable_list_view.dart
  lib/ui/widget/loading.dart
  lib/ui/widget/only_back_app_bar.dart
  lib/ui/widget/radio/radio_model.dart
  lib/ui/widget/rename_folder/show_rename_folder_dialog.dart
  lib/ui/widget/slidable/link_slidable_widget.dart
  pubspec.yaml
Labels: fix, refactor

#147 [LP-5-fix] Android에서 반응형으로 UI 사이즈 수정
  lib/main.dart
  lib/ui/page/home/home_page.dart
  lib/ui/page/my_folder/my_folder_page.dart
  lib/ui/page/my_page/my_page.dart
  lib/ui/view/links/home_view.dart
  lib/ui/view/links/link_detail_view.dart
  lib/ui/view/links/my_link_view.dart
  lib/ui/view/links/search_view.dart
  lib/ui/view/links/user_feed_view.dart
  lib/ui/view/report_view.dart
  lib/ui/view/splash_view.dart
  lib/ui/view/terms_view.dart
  lib/ui/view/tutorial_view.dart
  lib/ui/view/upload_view.dart
  lib/ui/view/user/change_profile_view.dart
  lib/ui/view/user/email_login_view.dart
  lib/ui/view/user/login_view.dart
  lib/ui/view/user/sign_up_job_view.dart
  lib/ui/view/user/sign_up_nickname_view.dart
  lib/ui/widget/add_folder/folder_add_title.dart
  lib/ui/widget/add_folder/horizontal_folder_list.dart
  lib/ui/widget/add_folder/show_add_folder_dialog.dart
  lib/ui/widget/add_folder/subtitle.dart
  lib/ui/widget/bottom_dialog.dart
  lib/ui/widget/bottom_toast.dart
  lib/ui/widget/buttons/bottom_sheet_button.dart
  lib/ui/widget/custom_reorderable_list_view.dart
  lib/ui/widget/dialog.dart
  lib/ui/widget/loading.dart
  lib/ui/widget/only_back_app_bar.dart
  lib/ui/widget/rename_folder/show_rename_folder_dialog.dart
  lib/ui/widget/slidable/link_slidable_widget.dart
  pubspec.yaml
Labels: refactor

#150 [LP-35-fix] Android 화면 오류 수정
  lib/ui/page/home/home_page.dart
  lib/ui/view/splash_view.dart
  lib/ui/view/upload_view.dart
Labels: fix

#154 [LP-7-feat] 툴팁 추가
  lib/cubits/tool_tip/my_link_upload_tool_tip_cubit.dart
  lib/cubits/tool_tip/upload_tool_tip_cubit.dart
  lib/provider/tool_tip_check.dart
  lib/routes.dart
  lib/ui/view/links/home_view.dart
  lib/ui/view/links/my_link_view.dart
  lib/ui/widget/scaffold_with_tool_tip.dart
  lib/ui/widget/shape/reverse_triangle_painter.dart
  lib/ui/widget/shape/triangle_painter.dart
  lib/ui/widget/widget_offset.dart
  lib/util/offset_utils.dart
Labels: feat

#153 [LP-10-fix] 마이링크/홈화면/피드화면 화면 스크롤 UI 작업
  lib/cubits/scroll/scroll_cubit.dart
  lib/routes.dart
  lib/ui/page/home/home_page.dart
  lib/ui/view/links/my_link_view.dart
  lib/ui/view/links/user_feed_view.dart
  lib/ui/widget/sliver/custom_header_delegate.dart
Labels: fix

#152 [LP-11-fix] 검색화면 결과 리스트 UI를 홈화면 리스트 UI와 동일하게 맞추는 작업
  lib/ui/view/links/search_view.dart
Labels: fix
